
[project]
name = "discord-bot"
version = "0.1.0"
description = "Discord bot with moderation, music, and search features"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "py-cord>=2.4.0",
    "googlesearch-python>=1.2.3",
    "beautifulsoup4>=4.12.0",
    "youtube-dl>=2021.12.17",
    "PyNaCl>=1.5.0",
    "async-timeout>=4.0.2",
]
